name: shop_us
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  badges: ^3.1.2
  stream_transform: ^2.1.0
  cached_network_image: ^3.3.1
  chat_bubbles: ^1.6.0
  country_code_picker: ^3.0.0
  custom_pop_up_menu: ^1.2.4
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_html: ^3.0.0-alpha.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  google_fonts: ^6.0.0
  grouped_list: ^5.1.2
  http: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.12
  timeago: ^3.6.1
  toggle_switch: ^2.1.0
  webview_flutter: ^4.2.2
  flutter_stripe: ^10.1.1
  flutter_font_awesome_web_names:
    git:
      url: https://github.com/Mythar/flutter_font_awesome_web_names
      ref: master
  flutter_credit_card: ^3.0.0  # Revert to a previous stable version
  shimmer: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  auto_size_text: ^3.0.0
  rename: ^3.0.1
  banner_carousel: ^1.2.1
  font_awesome_flutter: ^10.7.0
  dropdown_button2: ^2.3.9
  expandable_page_view: ^1.0.17

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/icons/
    - assets/image/
    - assets/images/
    - assets/stripe/
    - assets/launcher_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21
